# Site settings
title: NevTrace
description: 'The Blockchain lab'
url: 'http://nevtrace.com'
baseurl: '/'
google_analytics: 'UA-77064339-1'
disqus_shortname: 'nevtrace'

author:
  name: 'NevTrace'
  email: info@nevtrace.com
  twitter_username: nevtrace
  facebook_username: 
  github_username:  nevtrace
  linkedin_username:  nevtrace

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
